@echo off
cd /d "D:\JUMPINGGOOSE AI\JUMPINGGOOSEAI\JUMPINGGOOSEAI"
set "DB_TYPE=sqlite"
set "N8N_HOST=localhost"
set "N8N_PORT=5678"
set "N8N_RUNNERS_BROKER_PORT=5679"
set "N8N_PROTOCOL=http"
set "N8N_SECURE_COOKIE=false"
set "N8N_BLOCK_ENV_ACCESS_IN_NODE=false"
set "N8N_DIAGNOSTICS_ENABLED=false"
set "N8N_VERSION_NOTIFICATIONS_ENABLED=false"
npx.cmd n8n start
